apiVersion: v1
kind: Service
metadata:
  name: achmea-openshift-demo-sitecore-cd-s
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: achmea-openshift-demo-sitecore-cd
    deployment: achmea-openshift-demo-sitecore-cd-d
  sessionAffinity: None
  type: ClusterIP
